### PR TITLE
Raw Data (with the suggested changes)

### PR DESCRIPTION
**Pull request by diptanil-roy**
@emapple 
"1. We should probably include the code that was used to download these texts. If you can, please add them as scripts in the src, maybe as src/data.py."

-> I will include it, once I rewrite it as a script. At present, I have it in a notebook.

"2. Please get rid of the .DS_Store file, which we don't need to include."

-> Done in the latest commit.

" 3. Also, five files appear to have downloaded incorrectly (2 ibsen, 1 plato, and 2 shelley; if you type grep DOCTYPE * in the raw data directory, you'll see which ones)"

-> Addressed. It turns out that some books have a completely different URL. They are rare enough that I didn't see them before. I have included them now. Also, grep DOCTYPE * is a nice trick. Thanks.

### CODE REVIEW

**Review by emapple — CHANGES_REQUESTED** [review]
The `.DS_Store` file is still there. Remember, `rm` removes the file but it's still tracked by git. You have to do `git rm` to remove it as a tracked file. If you already deleted it but not from git, it's a bit more complicated, and you'll have to google it.

**Review by emapple — APPROVED** [review]

**Comment by diptanil-roy** [comment]
> The `.DS_Store` file is still there. Remember, `rm` removes the file but it's still tracked by git. You have to do `git rm` to remove it as a tracked file. If you already deleted it but not from git, it's a bit more complicated, and you'll have to google it.

There was another ".DS_Store" which I removed. Didn't notice the one that was in the main folder. Removed now.

**Comment by emapple** [comment]
@diptanil-roy did you do `git add *` or similar? I'd recommend against that going forward to avoid accidentally adding unwanted files. You could do, e.g., `git add *.txt` which would only add text files.

**Comment by diptanil-roy** [comment]
> @diptanil-roy did you do `git add *` or similar? I'd recommend against that going forward to avoid accidentally adding unwanted files. You could do, e.g., `git add *.txt` which would only add text files.

Yes, for the first commit, I used git add *. I will not use that anymore.

**Pull request merged**
