### PR TITLE
Add TOC reader

### PR DESCRIPTION
**Pull request by emapple**
Added a TOC reader, that is on by default.

It searches for an instance of "contents" or "table of contents" that constitutes its own line, and then finds the first instance after that of several new lines. Everything in between is the TOC, everything before is added to meta, and everything after is the text.

This isn't perfect, but TOC structure is too inconsistent to apply a more specific approach, like searching for "chapter" or "part".

### CODE REVIEW

**Comment by kdettman** [comment]
I admittedly haven't tested this yet, but what happens if the end of the TOC isn't three newline characters?

**Comment by emapple** [comment]
> I admittedly haven't tested this yet, but what happens if the end of the TOC isn't three newline characters?

In theory, it would either throw an error if it doesn't find them, or include a bunch of stuff that isn't actually TOC as TOC. However, I have yet to find a single case after a bunch of testing of a text that 1) includes a TOC and 2) doesn't end it with at least three newline characters

**Comment by kdettman** [comment]
Ok, if you haven't encountered any problems yet then its probably fine. We should just keep an eye out in case it does break.

**Review by kdettman — APPROVED** [review]

**Comment by emapple** [comment]
Sounds good! If we encounter problems, it'll be my job to fix it.

**Pull request merged**
