### PR TITLE
Final Analysis

### PR DESCRIPTION
**Pull request by diptanil-roy**
Processed datasets added, along with one notebook with all pipelines, and final results.

### CODE REVIEW

**Review by emapple — CHANGES_REQUESTED** [review]
This notebook looks great! I have one request - 

Can you create a single confusion matrix made from scoring all 4 test sets together as one? I think that should be our final figure.

**Review by NikhilTilak — APPROVED** [review]
Excellent job!

**Comment by diptanil-roy** [comment]
> This notebook looks great! I have one request -
> 
> Can you create a single confusion matrix made from scoring all 4 test sets together as one? I think that should be our final figure.

Addressed this.

**Review by emapple — APPROVED** [review]
Looks great!

**Pull request merged**
